package org.xmart.objc.frameworks.cocoa.Foundation;

import java.util.*;
import java.io.*;
import org.xmart.objc.type.*;
import org.xmart.objc.annotation.*;

@ObjCFramework("Foundation")
public enum NSXMLParserError {
    NSXMLParserInternalError($Foundation.NSXMLParserInternalError),
    NSXMLParserOutOfMemoryError($Foundation.NSXMLParserOutOfMemoryError),
    NSXMLParserDocumentStartError($Foundation.NSXMLParserDocumentStartError),
    NSXMLParserEmptyDocumentError($Foundation.NSXMLParserEmptyDocumentError),
    NSXMLParserPrematureDocumentEndError($Foundation.NSXMLParserPrematureDocumentEndError),
    NSXMLParserInvalidHexCharacterRefError($Foundation.NSXMLParserInvalidHexCharacterRefError),
    NSXMLParserInvalidDecimalCharacterRefError($Foundation.NSXMLParserInvalidDecimalCharacterRefError),
    NSXMLParserInvalidCharacterRefError($Foundation.NSXMLParserInvalidCharacterRefError),
    NSXMLParserInvalidCharacterError($Foundation.NSXMLParserInvalidCharacterError),
    NSXMLParserCharacterRefAtEOFError($Foundation.NSXMLParserCharacterRefAtEOFError),
    NSXMLParserCharacterRefInPrologError($Foundation.NSXMLParserCharacterRefInPrologError),
    NSXMLParserCharacterRefInEpilogError($Foundation.NSXMLParserCharacterRefInEpilogError),
    NSXMLParserCharacterRefInDTDError($Foundation.NSXMLParserCharacterRefInDTDError),
    NSXMLParserEntityRefAtEOFError($Foundation.NSXMLParserEntityRefAtEOFError),
    NSXMLParserEntityRefInPrologError($Foundation.NSXMLParserEntityRefInPrologError),
    NSXMLParserEntityRefInEpilogError($Foundation.NSXMLParserEntityRefInEpilogError),
    NSXMLParserEntityRefInDTDError($Foundation.NSXMLParserEntityRefInDTDError),
    NSXMLParserParsedEntityRefAtEOFError($Foundation.NSXMLParserParsedEntityRefAtEOFError),
    NSXMLParserParsedEntityRefInPrologError($Foundation.NSXMLParserParsedEntityRefInPrologError),
    NSXMLParserParsedEntityRefInEpilogError($Foundation.NSXMLParserParsedEntityRefInEpilogError),
    NSXMLParserParsedEntityRefInInternalSubsetError($Foundation.NSXMLParserParsedEntityRefInInternalSubsetError),
    NSXMLParserEntityReferenceWithoutNameError($Foundation.NSXMLParserEntityReferenceWithoutNameError),
    NSXMLParserEntityReferenceMissingSemiError($Foundation.NSXMLParserEntityReferenceMissingSemiError),
    NSXMLParserParsedEntityRefNoNameError($Foundation.NSXMLParserParsedEntityRefNoNameError),
    NSXMLParserParsedEntityRefMissingSemiError($Foundation.NSXMLParserParsedEntityRefMissingSemiError),
    NSXMLParserUndeclaredEntityError($Foundation.NSXMLParserUndeclaredEntityError),
    NSXMLParserUnparsedEntityError($Foundation.NSXMLParserUnparsedEntityError),
    NSXMLParserEntityIsExternalError($Foundation.NSXMLParserEntityIsExternalError),
    NSXMLParserEntityIsParameterError($Foundation.NSXMLParserEntityIsParameterError),
    NSXMLParserUnknownEncodingError($Foundation.NSXMLParserUnknownEncodingError),
    NSXMLParserEncodingNotSupportedError($Foundation.NSXMLParserEncodingNotSupportedError),
    NSXMLParserStringNotStartedError($Foundation.NSXMLParserStringNotStartedError),
    NSXMLParserStringNotClosedError($Foundation.NSXMLParserStringNotClosedError),
    NSXMLParserNamespaceDeclarationError($Foundation.NSXMLParserNamespaceDeclarationError),
    NSXMLParserEntityNotStartedError($Foundation.NSXMLParserEntityNotStartedError),
    NSXMLParserEntityNotFinishedError($Foundation.NSXMLParserEntityNotFinishedError),
    NSXMLParserLessThanSymbolInAttributeError($Foundation.NSXMLParserLessThanSymbolInAttributeError),
    NSXMLParserAttributeNotStartedError($Foundation.NSXMLParserAttributeNotStartedError),
    NSXMLParserAttributeNotFinishedError($Foundation.NSXMLParserAttributeNotFinishedError),
    NSXMLParserAttributeHasNoValueError($Foundation.NSXMLParserAttributeHasNoValueError),
    NSXMLParserAttributeRedefinedError($Foundation.NSXMLParserAttributeRedefinedError),
    NSXMLParserLiteralNotStartedError($Foundation.NSXMLParserLiteralNotStartedError),
    NSXMLParserLiteralNotFinishedError($Foundation.NSXMLParserLiteralNotFinishedError),
    NSXMLParserCommentNotFinishedError($Foundation.NSXMLParserCommentNotFinishedError),
    NSXMLParserProcessingInstructionNotStartedError($Foundation.NSXMLParserProcessingInstructionNotStartedError),
    NSXMLParserProcessingInstructionNotFinishedError($Foundation.NSXMLParserProcessingInstructionNotFinishedError),
    NSXMLParserNotationNotStartedError($Foundation.NSXMLParserNotationNotStartedError),
    NSXMLParserNotationNotFinishedError($Foundation.NSXMLParserNotationNotFinishedError),
    NSXMLParserAttributeListNotStartedError($Foundation.NSXMLParserAttributeListNotStartedError),
    NSXMLParserAttributeListNotFinishedError($Foundation.NSXMLParserAttributeListNotFinishedError),
    NSXMLParserMixedContentDeclNotStartedError($Foundation.NSXMLParserMixedContentDeclNotStartedError),
    NSXMLParserMixedContentDeclNotFinishedError($Foundation.NSXMLParserMixedContentDeclNotFinishedError),
    NSXMLParserElementContentDeclNotStartedError($Foundation.NSXMLParserElementContentDeclNotStartedError),
    NSXMLParserElementContentDeclNotFinishedError($Foundation.NSXMLParserElementContentDeclNotFinishedError),
    NSXMLParserXMLDeclNotStartedError($Foundation.NSXMLParserXMLDeclNotStartedError),
    NSXMLParserXMLDeclNotFinishedError($Foundation.NSXMLParserXMLDeclNotFinishedError),
    NSXMLParserConditionalSectionNotStartedError($Foundation.NSXMLParserConditionalSectionNotStartedError),
    NSXMLParserConditionalSectionNotFinishedError($Foundation.NSXMLParserConditionalSectionNotFinishedError),
    NSXMLParserExternalSubsetNotFinishedError($Foundation.NSXMLParserExternalSubsetNotFinishedError),
    NSXMLParserDOCTYPEDeclNotFinishedError($Foundation.NSXMLParserDOCTYPEDeclNotFinishedError),
    NSXMLParserMisplacedCDATAEndStringError($Foundation.NSXMLParserMisplacedCDATAEndStringError),
    NSXMLParserCDATANotFinishedError($Foundation.NSXMLParserCDATANotFinishedError),
    NSXMLParserMisplacedXMLDeclarationError($Foundation.NSXMLParserMisplacedXMLDeclarationError),
    NSXMLParserSpaceRequiredError($Foundation.NSXMLParserSpaceRequiredError),
    NSXMLParserSeparatorRequiredError($Foundation.NSXMLParserSeparatorRequiredError),
    NSXMLParserNMTOKENRequiredError($Foundation.NSXMLParserNMTOKENRequiredError),
    NSXMLParserNAMERequiredError($Foundation.NSXMLParserNAMERequiredError),
    NSXMLParserPCDATARequiredError($Foundation.NSXMLParserPCDATARequiredError),
    NSXMLParserURIRequiredError($Foundation.NSXMLParserURIRequiredError),
    NSXMLParserPublicIdentifierRequiredError($Foundation.NSXMLParserPublicIdentifierRequiredError),
    NSXMLParserLTRequiredError($Foundation.NSXMLParserLTRequiredError),
    NSXMLParserGTRequiredError($Foundation.NSXMLParserGTRequiredError),
    NSXMLParserLTSlashRequiredError($Foundation.NSXMLParserLTSlashRequiredError),
    NSXMLParserEqualExpectedError($Foundation.NSXMLParserEqualExpectedError),
    NSXMLParserTagNameMismatchError($Foundation.NSXMLParserTagNameMismatchError),
    NSXMLParserUnfinishedTagError($Foundation.NSXMLParserUnfinishedTagError),
    NSXMLParserStandaloneValueError($Foundation.NSXMLParserStandaloneValueError),
    NSXMLParserInvalidEncodingNameError($Foundation.NSXMLParserInvalidEncodingNameError),
    NSXMLParserCommentContainsDoubleHyphenError($Foundation.NSXMLParserCommentContainsDoubleHyphenError),
    NSXMLParserInvalidEncodingError($Foundation.NSXMLParserInvalidEncodingError),
    NSXMLParserExternalStandaloneEntityError($Foundation.NSXMLParserExternalStandaloneEntityError),
    NSXMLParserInvalidConditionalSectionError($Foundation.NSXMLParserInvalidConditionalSectionError),
    NSXMLParserEntityValueRequiredError($Foundation.NSXMLParserEntityValueRequiredError),
    NSXMLParserNotWellBalancedError($Foundation.NSXMLParserNotWellBalancedError),
    NSXMLParserExtraContentError($Foundation.NSXMLParserExtraContentError),
    NSXMLParserInvalidCharacterInEntityError($Foundation.NSXMLParserInvalidCharacterInEntityError),
    NSXMLParserParsedEntityRefInInternalError($Foundation.NSXMLParserParsedEntityRefInInternalError),
    NSXMLParserEntityRefLoopError($Foundation.NSXMLParserEntityRefLoopError),
    NSXMLParserEntityBoundaryError($Foundation.NSXMLParserEntityBoundaryError),
    NSXMLParserInvalidURIError($Foundation.NSXMLParserInvalidURIError),
    NSXMLParserURIFragmentError($Foundation.NSXMLParserURIFragmentError),
    NSXMLParserNoDTDError($Foundation.NSXMLParserNoDTDError),
    NSXMLParserDelegateAbortedParseError($Foundation.NSXMLParserDelegateAbortedParseError);

    private final long value;

    private NSXMLParserError(long value) { this.value = value; }
}
